apiVersion: v1
kind: Pod
metadata:
  name: simple-echo
spec:
  containers:
    - name: simple-echo
      image: gcr.io/thanawy/thanawy-nestjs-server:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
          hostPort: 8080