name: Build and Deploy to Google Cloud

on:
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_ID: thanawy
  SERVICE_ACCOUNT: github-actions@thanawy.iam.gserviceaccount.com

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/934017043258/locations/global/workloadIdentityPools/github-actions-pool/providers/thanawy-github-actions-provider'
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Build and push docker image
        uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          registry: gcr.io
          project_id: ${{ env.PROJECT_ID }}
          image_name: thanawy-nestjs-server
          image_tag: ${{github.event.issue.number}}

      - name: Deploy to Google Cloud
        uses: ghost-road-studio/deployment-manager@v0
        with:
          deployment: backend-server
          config: deploy/nestjs-server.yaml